### ISSUE TITLE
not working tracking control for v2.2.0

### ISSUE THREAD

**Issue by morkovin** [jijeshmohan/redmine_track_control#10]
Installation of the track_control  https://github.com/jijeshmohan/redmine_track_control/zipball/redmine2  which you mentioned in #7 (2.1.x support)  is successfull. I can see all the trackers in the roles/permissions and set the flag. I can also activer plugin for the project. The probrlem is traacker creation limitation does not work. All the users can create issues in the project for all the trackers. Flags in the roles/permissions are not taken in consideration by the plugin.
![Uploading v220_not_working.jpg . . .]()

**Comment by morkovin** [comment]
Please see some screens
![v220_not_working](https://f.cloud.github.com/assets/3116156/29836/9a54768c-4dd2-11e2-8c9c-d3053bcb4e7a.jpg)

**Comment by morkovin** [comment]
I've checked the sources and it looks strange for the totally disactivated/commented   RolePatch

Is it just a workaround solution or the bugfix? It looks strange for me

#Patches Redmine's Role.
module RolePatch
  def self.included(base)
    base.class_eval do
      unloadable
      #alias_method :permissions_without_unicode, :permissions unless method_defined? :permissions_without_unicode

```
  # def permissions
  # read_attribute(:permissions) || []
  # return [] unless self[:permissions]
  # self[:permissions].map! do |p|
  # if p.instance_of? String
  # p.split('').slice(1..-1).join.to_sym
  # else
  # p
  # end
  # end
  # end
end
```

  end
end

**Comment by jijeshmohan** [comment]
Hi 

You can take the latest build  https://github.com/jijeshmohan/redmine_track_control/archive/redmine2.zip

Regards,
Jijesh

**Comment by morkovin** [comment]
Thanks a lot! We will test it after New Year :)
