### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by cforce** [jijeshmohan/redmine_track_control#11]
Can us please add some words what was your pain/goal to solve/achieve with this plugin.
In fact enabling or disabling tracker control is allready possible with redmine core workflow control, so what does this plugin help to do beyond. Would be great o make this clear, so someone knows what hw wins when using it.

Tx for ur work.!

**Comment by jijeshmohan** [comment]
Hi,

I has been stated in the blog link which i have provided in this project itself. [here](http://jijeshmohan.wordpress.com/2011/12/24/redmine-tracker-control-plugin-released/).  Workflow will not restrict you to create an issue with a specific tracker. for eg. I dont want my users to create an issue with Feature tracker but can create bug.

I will add more details in the README itself. 

Thanks

**Comment by cforce** [comment]
Ah, i see. Yes that is needful but should be part of the core. Someone could see it as bug more than a feature.
If workflow has no start state enabled for role there should be no tracker entry in drop down.

**Comment by cforce** [comment]
Is there a correspdonding issue on redmine.org?

**Comment by jijeshmohan** [comment]
I have checked for any existing feature request or bug before creating this plugin but I was not able to find anything.

It will be great if we can add this feature/bug fix to redmine.

**Comment by morkovin** [comment]
AFAIK redmine declined such requests according to idea that methodolgy of the ussue tracking should not forbid any access to tha trackers inside the Team. Maybe I am not correct about the reason, but I remember that there was a statement NOT TO IMPLEMENT such restriction in the core.
I agree that it SHOULD BE in the core like you said "If workflow has no start state enabled for role there should be no tracker entry in drop down."

**Comment by cforce** [comment]
I created an issue . http://www.redmine.org/issues/12718

Please vote for it.

**Comment by Cissi** [comment]
Hello, they closed your issue and refered to this one instead, maybe you can add your code as a patch to that issue so that it will be part of the redmine core, They tend to take in things that are tested and used.

http://www.redmine.org/issues/7839 

Or at least refer to the plugin as a patch... Of you want that. I would love to see it be part of the core.
