### ISSUE TITLE
Default behavior when the module is not enabled.

### ISSUE THREAD

**Issue by dipanm** [jijeshmohan/redmine_track_control#14]
As per what I see in documentation, in the project where Tracker control is not enabled, all trackers should be allowed - rather, as I see - no tracker is allowed when the module is disabled. 

![new-issue-tracker](https://f.cloud.github.com/assets/4157091/437139/9b3bb266-b08f-11e2-8d9f-8c0e546a2b49.jpg)

**Comment by jijeshmohan** [comment]
Thanks for reporting this defect. Will fix soon.

**Comment by jijeshmohan** [comment]
Fixed the defect. Hope it is working for you now.
