### ISSUE TITLE
Track Control affects the listing of custom fields on the first load.

### ISSUE THREAD

**Issue by dipanm** [jijeshmohan/redmine_track_control#17]
I am not sure if I am exactly representing the problem crisply - so I am putting it as exact behavior. 

Basically, we have customer-rep. type field to report errors. This may or may not be actual bug - so we don't allow the customer-rep to file bug - but as event. The dev team can file event as well as bug and other trackers. 

We heavily use custom-field and field-level-workflow to ensure people file right details at the right time. Event has a unique set of fields mostly for itself. Many of them are *required at the time of filing the report. 

When customer-reps fills the form - it doesn't see, at first, those fields which are unique  to the event. However, as he submits the page - the error shows up saying fields "xyz" are *required. Dev people usually don't find this issue! 

Issue doesn't exists if track_controll is disabled. Though, I don't know what is really wrong. 

Will provide more details to reproduce problems as you ask for.

**Comment by danieleped** [comment]
This seems to be linked with issue #20 , the one I reported yesterday. 

Any news?

**Comment by terrones** [comment]
Check comments on issue #22 in fact the change I have posted is the actual you need for fix that behavior, in redmine 2.5.x (we also implemented changes posted as comments for that issue for getting plugin working fine)

**Comment by jijeshmohan** [comment]
Fixed #22 . Closing this issue since it is related.
