### ISSUE TITLE
Question about functionality (visiblity and accessability)

### ISSUE THREAD

**Issue by alterdaemon** [jijeshmohan/redmine_track_control#24]
Hi
I am not sure about one thing:

If I choose some role to not being able to create a issue on specificc tracker, does the side effect is that the role doesn't see and can't access this tracker either?
- because that's the functionality I am looking for.

I am using now a redmine_tracker_accessible which manages visibiliy and access in a great way but is unfotunately  not compatible with the extended_watchers plugin...

**Comment by jijeshmohan** [comment]
This plugin's scope is only for controlling tracker wise issue creation. Not controlling the visibility of issues. I will try to experiment with controlling visibility of issues in this plugin, but can't promise anything right now.
