### ISSUE TITLE
Don't show trackers that are disabled for some roles.

### ISSUE THREAD

**Issue by hitzel** [jijeshmohan/redmine_track_control#6]
Is it possible if the tracker is disabled for a role to not show de tracker at all? Example the reporter has only the tracker support, so he can only choose the tracker support en doesn't see the other trackers.

This would be a great extra for our company.

**Comment by jijeshmohan** [comment]
While creating a new issue, it shows only the trackers which belongs to the user. Please check whether the module is enabled in Project settings -> Module tab. 

Let me know if the problem still exists.

**Comment by hitzel** [comment]
I have restarted the server and it works. Thanks for the support
