### ISSUE TITLE
Support 2.1.x

### ISSUE THREAD

**Issue by hitzel** [jijeshmohan/redmine_track_control#7]
is it possible to support Redmine 2.1.x? I'm getting error when i am unpacking.

Rake aborted!
undefined method 'permissions'  for class 'Role'

**Comment by jijeshmohan** [comment]
In redmine 2.1.x the architecture changed which is causing this error. Will work on this.

**Comment by hitzel** [comment]
How much work is it? Any idea when it's ready?

**Comment by jijeshmohan** [comment]
Hopefully by this weekend.

**Comment by jijeshmohan** [comment]
Fixed the problem, you can download the plugin from [here](https://github.com/jijeshmohan/redmine_track_control/zipball/redmine2). Known issue: If there is tracker with unicode name ( non-english) , unable to set the permission for that.

**Comment by hitzel** [comment]
Thank you very much.
