### ISSUE TITLE
compatibility for redmine 2.1.4 ? knows bugs?

### ISSUE THREAD

**Issue by cforce** [jijeshmohan/redmine_track_control#9]

**Comment by jijeshmohan** [comment]
Hi

[#8](https://github.com/jijeshmohan/redmine_track_control/issues/8) is the known bug in this.

**Comment by Cissi** [comment]
Does this mean you can use it in Redmine 2.1.4? I would like to upgrade but cannot do it unless your plugin is working as well...

**Comment by morkovin** [comment]
I think you can. We do it in our team on 2.1.5.stable

**Comment by jijeshmohan** [comment]
I haven't tested in 2.2 yet. but should work in 2.1.x . If your tracker names are english characters and there are no space in between , you can use the plugin right now. I will try to test in 2.2 this weekend.

**Comment by morkovin** [comment]
we tested for 2.2. but failed. plugin can be installed but doesn't work. Please see separate issue https://github.com/jijeshmohan/redmine_track_control/issues/10

**Comment by jijeshmohan** [comment]
Hi 

It is working with 2.2 now. https://github.com/jijeshmohan/redmine_track_control/archive/redmine2.zip 

But the defect #8 still exists.

**Comment by jijeshmohan** [comment]
#8 : fixed partially , now tracker name with spaces will work. yet to fix the unicode problem.
